//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHanh
    {
        public int Id { get; set; }
        public string Product_name { get; set; }
        public Nullable<System.DateTime> Warranty_date { get; set; }
        public string Recipient_phoneNumber { get; set; }
        public string Recipient_address { get; set; }
        public string Error_Details { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> SaleOrderId { get; set; }
    }
}
