//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Sale_price { get; set; }
        public string Short_description { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Create_by { get; set; }
        public string Update_by { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Is_hot { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
    }
}
