//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Create_by { get; set; }
        public string Update_by { get; set; }
        public Nullable<byte> status { get; set; }
        public string Customer_name { get; set; }
        public string Customer_address { get; set; }
        public string Customer_mobile { get; set; }
        public string Customer_email { get; set; }
    }
}
